---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.3
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: An open-source programming language supported by Google
app_name: go
app_repo: https://github.com/golang/go
app_type: standalone
app_website: https://go.dev/
archive_conf_path: ''
archive_conf_strip: 1
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://dl.google.com/go/go{version}.{os}-{arch}.tar.gz.sha256
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]?rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://dl.google.com/go/go{version}.{os}-{arch}.tar.gz
gpg_enabled: false
install_map_enabled: false
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-golang
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-golang.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv5
    armv6*: armv6
    armv7*: armv7
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: version
version_file_enabled: true
version_file_names: go.mod go.work
version_prefix: go
