---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3-40-g54b0db0
_src_path: /Users/kamontat/Desktop/Personal/asdf-plugin-template
app_desc: An open-source programming language supported by Google
app_name: go
app_repo: https://github.com/golang/go
app_website: https://go.dev/
archive_conf_path: ''
archive_conf_strip: 1
archive_enabled: true
archive_regex: (\.tar\.gz|\.tgz|\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://dl.google.com/go/go{version}.{os}-{arch}.tar.gz.sha256
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]?rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://dl.google.com/go/go{version}.{os}-{arch}.tar.gz
gpg_enabled: false
install_map_enabled: false
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-golang
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-golang.git
source_enabled: false
test_cmd_args: version
version_file_enabled: true
version_file_names: go.mod go.work
version_prefix: go
